### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by hurzl** [hampelratte/lazybones#12]
```
java.util.ConcurrentModificationException
  at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
  at java.util.ArrayList$Itr.next(ArrayList.java:851)
  at lazybones.TimerManager.getTimer(TimerManager.java:240)
  at lazybones.LazyBones.getProgramTableIcons(LazyBones.java:859)
  at tvbrowser.core.plugin.JavaPluginProxy.doGetProgramTableIcons(JavaPluginProxy.java:474)
  at tvbrowser.core.plugin.AbstractPluginProxy.getProgramTableIcons(AbstractPluginProxy.java:450)
  at util.ui.ProgramPanel.getPluginIcons(ProgramPanel.java:687)
  at util.ui.ProgramPanel.paintComponent(ProgramPanel.java:712)
  at javax.swing.JComponent.paint(JComponent.java:1056)
  at util.ui.ProgramPanel.paint(ProgramPanel.java:1180)
  at tvbrowser.ui.programtable.ProgramTable.paintComponent(ProgramTable.java:411)
  at javax.swing.JComponent.paint(JComponent.java:1056)
  at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
  at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:290)
  at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
  at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
  at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
  at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
  at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
  at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
  at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
  at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
  at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
  at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
  at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
  at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
  at java.awt.EventQueue.access$500(EventQueue.java:97)
  at java.awt.EventQueue$3.run(EventQueue.java:709)
  at java.awt.EventQueue$3.run(EventQueue.java:703)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
  at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
  at util.ui.textcomponentpopup.TextComponentPopupEventQueue.dispatchEvent(TextComponentPopupEventQueue.java:55)
  at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
  at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
  at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
  at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by hampelratte** [comment]
Kannst Du die Situation beschreiben, wann der Fehler auftrat? Ist TV-Browser gerade erst gestartet, oder läuft er schon eine Weile. Was hast Du in dem Moment gemacht?

**Comment by hurzl** [comment]
Ich glaube, ich habe eine Sendung programmiert und er hatte vor 1-2 Minuten neu gestartet nach Update von lazybones. Kam mehrfach aber nicht reproduzierbar.

**Comment by hampelratte** [comment]
Ja, der ist leider nur schwer reproduzierbar, weil er nur auftritt, wenn zwei Threads gleichzeitig auf die Liste der Timer zugreifen. Den einen Thread sehen wir im Log, von dem anderen wissen wir nichts. Daher kann man nur mutmaßen, was eventuell der Auslöser war. Ich schaue mir den Code mal an, vielleicht finde ich was.

**Comment by hampelratte** [comment]
Ich habe gerade Version 1.5.2 hochgeladen, in der ich ein paar Änderungen in der Timer-Verwaltung vorgenommen habe. Ich schließe das Ticket jetzt erst mal. Wenn der Fehler wieder auftritt, kannst Du es gerne wieder öffnen.
